use serde::{Deserialize, Serialize};

use crate::*;

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskFinishParams {
    /// Unique id of the task with optional reference to parent task id
    pub task_id: TaskId,
    /// A unique identifier generated by the client to identify this request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub origin_id: Option<Identifier>,
    /// Timestamp of when the event started in milliseconds since Epoch.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_time: Option<i64>,
    /// Message describing the task.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Task completion status.
    pub status: StatusCode,
    /// Optional metadata about the task.
    /// Objects for specific tasks like compile, test, etc are specified in the protocol.
    #[serde(flatten, skip_serializing_if = "Option::is_none")]
    pub data: Option<TaskFinishData>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tests::*;
    use insta::assert_json_snapshot;

    #[test]
    fn task_finish_params() {
        assert_json_snapshot!(
           TaskFinishParams {task_id: TaskId::default(), origin_id: Some(Identifier::default()), event_time: Some(TEST_LONG), message: Some(TEST_STRING.to_string()), status: StatusCode::default(), data: Some(TaskFinishData::Other(OtherData::default()))},
           @r#"
{
  "taskId": {
    "id": ""
  },
  "originId": "",
  "eventTime": 2,
  "message": "test_string",
  "status": 1,
  "dataKind": "",
  "data": null
}
   "#
        );
    }
}
