use serde::{Deserialize, Serialize};

use crate::*;

/** `ScalaDiagnostic` is a data structure that contains Scala-specific
metadata generated by Scala compilation. */
#[derive(Debug, PartialEq, Eq, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScalaDiagnostic {
    /** Actions (also known as quick fixes) that are able to either fix or address
    the issue that is causing this diagnostic. */
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub actions: Vec<ScalaAction>,
}
